buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        google()
    }
    dependencies {
        classpath libs.robovm.gradle.plugin
    }
}

apply plugin: "java-library"
apply plugin: "robovm"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

sourceSets.main.java.srcDirs = [ "src/" ]

ext {
	mainClassName = "com.azkh.blackbox.IOSLauncher"
}

dependencies {
    implementation project(":core")
    api libs.robovm.rt
    api libs.robovm.cocoatouch
    api libs.gdx.backend.robovm
    api libs.gdx.platform
    api libs.gdx.freetype.platform
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build

robovm {
	archs = "thumbv7:arm64"
}

eclipse.project.name = appName + "-ios"
